            - name: Test Hello vooloJoxoh3o
  # You may pin to the exact commit or the version.
  # uses: szksh-lab-2/hello-action-2@b8ff704aeaf6880542354c29ad758bd0cdc72234
  uses: szksh-lab-2/hello-action-2@v0.0.2
          
