name: demo app

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy_on_aws:
    runs-on: self-hosted

    steps:

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::174331605686:role/allow-ssmaccess_to_github_runners
          role-session-name: github-actions
          aws-region: ap-south-1

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-07eb7aed4fc26e89a" \
            --document-name "custom_doc"
